import {
  Bot,
  BrainCircuit,
  BriefcaseBusiness,
  ChartNoAxesCombined,
  CheckCircle2,
  ClipboardCheck,
  CloudCog,
  Code2,
  Database,
  FileCheck2,
  FileText,
  Gauge,
  Globe2,
  Handshake,
  Headphones,
  Layers3,
  LockKeyhole,
  Mail,
  MessageSquareText,
  Network,
  PanelTop,
  PlugZap,
  RefreshCw,
  Route,
  Send,
  ServerCog,
  Settings2,
  ShieldCheck,
  Sparkles,
  TableProperties,
  TimerReset,
  Users,
  Webhook,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  bot: Bot,
  brain: BrainCircuit,
  business: BriefcaseBusiness,
  chart: ChartNoAxesCombined,
  check: CheckCircle2,
  clipboard: ClipboardCheck,
  cloud: CloudCog,
  code: Code2,
  database: Database,
  document: FileText,
  fileCheck: FileCheck2,
  gauge: Gauge,
  globe: Globe2,
  handshake: Handshake,
  headphones: Headphones,
  layers: Layers3,
  lock: LockKeyhole,
  mail: Mail,
  message: MessageSquareText,
  network: Network,
  panel: PanelTop,
  plug: PlugZap,
  refresh: RefreshCw,
  route: Route,
  send: Send,
  server: ServerCog,
  settings: Settings2,
  shield: ShieldCheck,
  sparkles: Sparkles,
  table: TableProperties,
  timer: TimerReset,
  users: Users,
  webhook: Webhook,
  workflow: Workflow,
  zap: Zap,
};

export function AutomationIcon({
  name,
  size = 22,
}: {
  name: string;
  size?: number;
}) {
  const Icon = icons[name] ?? Workflow;
  return <Icon aria-hidden="true" size={size} strokeWidth={1.8} />;
}
